### ISSUE TITLE
Feature Request: Row Grouping

### ISSUE THREAD

**Issue by zaktimson** [swimlane/ngx-datatable#429] opened 2017-01-13 21:33 UTC
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here
```
Row grouping based on like properties. I am using this table to load in massive amounts of data, as much as 16k rows. I would like to be able to have these condensed into groups based on defined an array of defined properties (So that I can have groups within groups). For example if I had a list of cities and wanted to group the rows first by country and then by city.

```
data = [
    {company: 'aaa', city: 'Berlin', country: 'Germany'},
    {company: 'bbb', city: 'Berlin', country: 'Germany'},
    {company: 'ccc', city: 'Aachen', country: 'Germany'},
]

...

<ngx-datatable [rows]="data" [groupBy]="[{name: 'Country'}, {name: 'City', prop: 'city'}]" ...
```
![](http://www.jqwidgets.com/wp-content/uploads/2012/01/jquery-grid-grouping.png)

**Comment by amcdnl** [comment] 2017-01-13 22:12
Dupe of #35

**Closed** 2017-01-13 22:12 UTC
Labels: Duplicate
