### ISSUE TITLE
Summary / Total Row

### ISSUE THREAD

**Issue by AlexSpirin1990** [swimlane/ngx-datatable#216] opened 2016-10-21 11:47 UTC
Can I add total row ? This line needs to show total values column.

**Comment by istiti** [comment] 2016-10-21 12:08
Do you mean `footerHeight` option

**Comment by amcdnl** [comment] 2016-10-21 12:32
Like a summary row?

**Comment by AlexSpirin1990** [comment] 2016-10-21 12:52
Yes, like a summary row.

**Comment by amcdnl** [comment] 2016-10-21 13:23
Not really possible at the moment, but something I would be happy to help you if you want to PR

**Comment by Tempus35** [comment] 2016-10-25 17:30
Just thought I would point out this is likely the same as my request here #115

**Comment by amcdnl** [comment] 2017-04-15 13:33
Dupe of #115

**Closed by amcdnl** 2017-04-15 13:33 UTC
Labels: Accepting PRs, New Feature
