### ISSUE TITLE
Error when application starts 

### ISSUE THREAD

**Issue by lpunderscore** [swimlane/ngx-datatable#779] opened 2017-05-27 23:08 UTC
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
After setting up the basics, I created a component with a datatable. When the application first loads, I get a bunch of errors like:

> Exception: Call to Node module failed with error: Error: Template parse errors:
> Can't bind to 'rows' since it isn't a known property of 'ngx-datatable'.
> 1. If 'ngx-datatable' is an Angular component and it has 'rows' input, then verify that it is part of this module.
> 2. If 'ngx-datatable' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
> 3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.

If I just comment out the html definition inside the component template where the table is defined, then the application loads properly.

Now here is the funny part: If I un-comment the html definition, the page will reload and the table works, data is loaded properly. If I refresh the app, I get the errors again.

**Expected behavior**
The table would load correctly when the application first starts.

**Reproduction of the problem**
Create a new project using microsoft.aspnetcore.spatemplates, Add ngx-datatable; create a component with a datatable, start app.

**Please tell us about your environment:**
Used the microsoft.aspnetcore.spatemplates to generate the app. Using node v6.10.3, npm v3.10.10, angular 4.1.2

* **Table version:** 0.8.x
9.2.0

* **Angular version:** 2.0.x
Angular 4.1.2

* **Browser:** 
Chrome Version 58.0.3029.110 (64-bit)

**Comment by sheiidan** [comment] 2017-05-28 19:13
Make sure you imported the module into your app's module:

import { NgxDatatableModule } from "@swimlane/ngx-datatable";

.
.
.

imports: [
    NgxDatatableModule 
]

**Comment by lpunderscore** [comment] 2017-05-29 01:05
@sheiidan, Yeah this is basic setup stuff and has been done. Like I said, if I uncomment the datatable html the app will refresh and the datatable works juste fine.... If I hit F5 to reload the app, then i get the errors again.

**Comment by lpunderscore** [comment] 2017-05-30 03:33
Ok...

The template uses server pre rendering, which is causing the datatable to fail. Datatable seems to be trying to access browser primitives or DOM which it really should not do. 

For anyone having this issue, the "fix" is to remove the prerender tag of the index.cshtml.

<app @*asp-prerender-module="ClientApp/dist/main-server"*@>Loading...</app> (notice the asp-prerender-module is commented out.

**Comment by amcdnl** [comment] 2017-08-04 13:39
We do not support sever-side rendering. I would consider that a dupe of that issue. If thats not the case, please let me know and i'll reopen.

**Closed by amcdnl** 2017-08-04 13:39 UTC
