### ISSUE TITLE
virtual scrolling with server side retrieval

### ISSUE THREAD

**Issue by ipassynk** [swimlane/ngx-datatable#180] opened 2016-10-04 20:10 UTC
**I'm submitting a ...**  (check one with "x")

```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
I am trying to figure out how to do virtual scrolling with server side retrieval. I tried to do:
a. add externalPaging and it does not work virtual scrolling
a. add (onPageChange)='onPage($event)' with virtual scrolling but i always get page=undefined and offset, limit, count are the same.

**Expected behavior**
Receive different offset to load additional data from a server

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**
Virtual scrolling with server side retrieval

**Please tell us about your environment:**

- **Table version:** 0.7.x
  
  
- **Angular version:** 2.0.x
  
  
- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  
  
- **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by amcdnl** [comment] 2016-10-04 20:40
Can you make a demo of what you're proposing ( even if it doesn't work )?

**Comment by ipassynk** [comment] 2016-10-04 22:56
I might be wrong about offset params. I will try to create a demo. 

Howevere, here is an example how kendo grid implements virtual scrolling with remote data: http://demos.telerik.com/kendo-ui/grid/virtualization-remote-data

**Comment by ipassynk** [comment] 2016-10-05 03:43
I was able to make an initial/dirty version of virtual scroll with angular2-data-table. I have several questions marked with TODO. 
here is the code:
https://plnkr.co/edit/W71NajSAiMy6a3SIP9LF?p=preview

**Comment by deeg** [comment] 2017-01-26 20:56
This is related to / a duplicate of #353

**Comment by amcdnl** [comment] 2017-01-27 16:13
Closing as duplicate.

**Closed by amcdnl** 2017-01-27 16:13 UTC
Labels: In Discussion, Investigate, Need More Info
