### ISSUE TITLE
Empty detail row

### ISSUE THREAD

**Issue by cortopy** [swimlane/ngx-datatable#425] opened 2017-01-11 13:13 UTC
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
I'm trying to replicate the demo for the detail row example. Everything works as it should (main rows display ok, I can toggle detail row, etc.)

**Expected behavior**
There would be some content in detail row, however it's empty.

**Reproduction of the problem**
I'm using the following HTML. It's exactly the same as per the demo, with the only difference that to make sure it works, I put just plain text.

```html
    <ngx-datatable-row-detail>
      <template let-row="row" ngx-datatable-row-detail-template>
        <div style="padding-left:35px;">
          <h2>JUST PURE TEXT</h2>
        </div>
      </template>
    </ngx-datatable-row-detail>
```

**Please tell us about your environment:**
Fedora

* **Table version:** 0.7.x
4.1.0

* **Angular version:** 2.0.x
2.4.2
* **Browser:** all

* **Language:**
Typescript 2.1.4

**Comment by cortopy** [comment] 2017-01-11 13:42
I've just replicated this behaviour with the demo app.

Steps to reproduce:
- Clone repo
- npm install
- npm start

![screenshot from 2017-01-11 13-41-11](https://cloud.githubusercontent.com/assets/8725825/21850685/b035868e-d803-11e6-953f-a2e23ff47f6d.png)

**Comment by tsm91** [comment] 2017-01-12 15:50
Got the same behavior. :/

Fix this asap pls

**Comment by astenuz** [comment] 2017-01-14 11:41
I'm facing the same issue. The expanded event is correctly fired. Looking at the `DataTableRowWrapperComponent`, the container with the condition `*ngIf="expanded"` is rendered, but the template `rowDetailTemplate` is null. Thus the condition `*ngIf="rowDetailTemplate"` is always false and nothing is rendered.

**Comment by astenuz** [comment] 2017-01-14 17:45
I've founda temporary solution defining the ´DatatableRowDetailDirective´ yourself in the component you're defining the table and then passing it to the ´<ngx-datatable>´ selector.

In your component you'll have something along
```typescript
@ViewChild(DatatableRowDetailDirective) rowDetail: DatatableRowDetailDirective;
template: TemplateRef<any>;
...
ngOnInit(){
    this.template = this.rowDetail.template;
  }
```
and in your component's template

```html
<ngx-datatable
        #mydatatable
        ...
        [rowDetailTemplate]='template'
       ...
```

The bug seems to be caused because in the method `set rowDetailTemplateChild(val: DatatableRowDetailDirective)` of datatable.component.ts `val.rowDetailTemplate` is `null`. Not sure why. Perhaps because it hasn't been rendered yet and it is necessary to do it after `ngOnInit()`?

**Comment by astenuz** [comment] 2017-01-14 18:20
It worked after i replaced the `ngOnInit` datatable component with

```typescript
  ngOnInit(): void {
    // need to call this immediatly to size
    // if the table is hidden the visibility
    // listener will invoke this itself upon show
    this.recalculate();
    if(this.rowDetailTemplateChild)
      this.rowDetailTemplate = this.rowDetailTemplateChild.rowDetailTemplate;
  }
```
Seems like the val.rowDetailTemplate is not defined yet when `set rowDetailTemplateChild(val: DatatableRowDetailDirective)` is called.

**Comment by amcdnl** [comment] 2017-01-17 13:46
Fixed in 5.0

**Closed by amcdnl** 2017-01-17 13:46 UTC
Labels: Bug, Investigate, Priority: High

**Comment by kuncevic** [comment] 2017-02-02 03:01
Got in to that issue once updated the angular version to 2.5.0 using ngx-datatable 4.0.0.
So the issue is fixed in ngx-datatable 5.0.0 as stated above.

But there some breaking changes you have to be aware of going from verson 4 to version 5:

**.ts**
`this.table.expandAllRows();` => `this.table.rowDetail.expandAllRows();`
`this.table.toggleExpandRow(row);`' => `this.table.rowDetail.toggleExpandRow(row);`

**template:**
`ngx-datatable`  `[detailRowHeight]="xxx"` property moved to `ngx-datatable-row-detail` property as `[rowHeight]="xxx"`

**Comment by amcdnl** [comment] 2017-02-02 13:20
FYI -> These are documented in docs/changelog

**Comment by kuncevic** [comment] 2017-02-02 21:18
@Amcdl I just looked through the demo source :)

**Comment by psreeks** [comment] 2017-03-24 19:31
@amcdnl @kuncevic is there a way to have all the rows expanded by default? expand all and collapse all are working as expected as shown in demo. But this triggers only on click event.
