### ISSUE TITLE
ERROR in There is no format with import statements in 'C:/ANGULAR/project-angular/node_modules/@swimlane/ngx-datatable' entry-point

### ISSUE THREAD

**Issue by yuveliremil** [swimlane/ngx-datatable#1699] opened 2019-05-31 11:52 UTC
After enabled Ivy :

"angularCompilerOptions": {
    "enableIvy": true, 
    "allowEmptyCodegenFiles": true
  }

Error:

ERROR in There is no format with import statements in 'C:/ANGULAR/azi/node_modules/@swimlane/ngx-datatable' entry-point.

**Comment by christianrondeau** [comment] 2019-05-31 14:07
Refer to https://github.com/angular/angular/issues/29564 for more information; this affects multiple packages with ivy

**Comment by marjan-georgiev** [comment] 2019-06-03 13:04
Looks like this affects multiple angular libraries that don't use angular cli. We plan to migrate ngx-datatable to angular cli soon, so that should resolve this issue. If anyone knows how to do a quick fix to enable ivy until then, a PR is welcome.

**Comment by mhadji** [comment] 2019-06-03 13:55
I like "soon" in your comment. we use ngx-datatable vastly in our project. the project upgraded to V8 with no problem but we couldn't enable Ivy for the exact same reason.

**Comment by moepkid** [comment] 2019-06-04 13:01
@marjan-georgiev great to hear! we use the library alot so its great to hear that the upgrade will come soon. Do you have an ETA or something? Btw, amazing work you guys do :D

**Comment by WillHall** [comment] 2019-06-04 21:07
```
ERROR in node_modules/@swimlane/ngx-datatable/release/datatable.module.d.ts(1,22): error TS-996002: Appears in the NgModule.imports of MyModule, but could not be resolved to an NgModule class
```

I managed to get around this issue by extracting the src folder and including it as a regular module in my lib until swimlane publishes a new version.

However, now that the build will run - we learn that IVY doesn't like this stuff:

```
  @Input()
  @ContentChild(DataTableFooterTemplateDirective, {
    read: TemplateRef,
    static: false
  })
  template: TemplateRef<any>;
```
ERROR in Cannot combine @Input decorators with query decorators

This occurs in:
footer.directive.ts
column.directive.ts
body-group-header.directive.ts
row-detail.directive.ts

removing @Input() before each @ContentChild solves this, but I assume this will prevent the template overrides from working (??) whatever, removing them gets you past any data-table issues so you can fix other stuff while we wait.

**Comment by marjan-georgiev** [comment] 2019-06-10 09:39
@WillHall thank you for looking into that. I am guessing we can split those into two separate properties.

**Comment by marjan-georgiev** [comment] 2019-06-10 10:25
@WillHall looks like this has already been looked at by @alxhub and there's a PR for it here: https://github.com/swimlane/ngx-datatable/pull/1660

**Comment by bleuscyther** [comment] 2019-06-12 23:50
I have the error in version 15.0.2

**Comment by bleuscyther** [comment] 2019-06-13 01:48
Installing : 
````console
 npm install @angular/compiler-cli@next
````
seems to resolve the issue

**Comment by shiamalon** [comment] 2019-06-17 10:04
I wanted to  test Ivy but got the same issue with   "@swimlane/ngx-datatable": "^15.0.2"

**Comment by guyng** [comment] 2019-06-23 21:39
same here, you need to make a fix asap

**Comment by majhoos** [comment] 2019-06-24 22:21
Could someone come up with a time-scale on this? 24 days for such a critical issue is more than enough and this bug has to be addressed as quickly as possible.

**Comment by guyng** [comment] 2019-06-24 23:57
@marjan-georgiev any news?

**Comment by GlauberF** [comment] 2019-07-02 19:03
I updated to version 15.0.2, but the error continues, news?

**Comment by fabrizziocht** [comment] 2019-07-02 19:49
Any solution for this problem??

**Comment by bleuscyther** [comment] 2019-07-03 23:56
i think they are being fixed https://github.com/angular/angular/issues/29564 an d https://github.com/angular/angular/issues/31394 . After today's angular's update many issues seemed fixed, but there is one last issue affecting many packages

**Comment by whyboris** [comment] 2019-07-22 18:54
Thank you to `ngx-datatable` team for the continued work. As far as I can tell currently this is still broken with version `15.0.2` and with Angular enabled with *Ivy* (`8.2.0-next.1`).

It's possible that fixing it is not too bad:
https://github.com/angular/angular/issues/29564#issuecomment-480730674
> The fix is that the package author needs to export this type publicly, e.g.re- export it from the `release/datatable.module.d.ts` file.

It's possible that a solution can come from using `[ng-packagr](https://github.com/ng-packagr/ng-packagr)`:
https://github.com/angular/angular/issues/29564#issuecomment-480472933

Since _Ivy_ is still an experimental feature not to be released officially until October / November 2019 we still have a lot of time before it's really pressing to fix. But a fix before then would be very appreciated 🙇

**Comment by whyboris** [comment] 2019-08-01 19:04
I tried again today with the latest:
- Angular `9.0.0-next.0`
- AngularCLI `8.3.0-next.0`
No success:
```
ERROR in node_modules/@swimlane/ngx-datatable/release/datatable.module.d.ts(1,22): error TS-996002: Appears in the NgModule.imports of AdminModule, but could not be resolved to an NgModule class
```
🤷‍♂

**Comment by whyboris** [comment] 2019-08-13 18:39
Tried again today with the latest:
- Angular `9.0.0-next.2`
- AngularCLI `8.3.0-next.1`
- Angular/compiler-cli `9.0.0-next.2`
No success:
> ERROR in node_modules/@swimlane/ngx-datatable/release/datatable.module.d.ts(1,22): error TS-996002: Appears in the NgModule.imports of AdminModule, but could not be resolved to an NgModule class
😞

**Comment by marjan-georgiev** [comment] 2019-09-05 14:36
This should be fixed in 16.0.0. Could someone verify please?

**Closed by marjan-georgiev** 2019-09-05 14:36 UTC
Labels: Bug

**Comment by whyboris** [comment] 2019-09-05 15:55
I am unsure whether there are still problems, but there's certainly progress. I am getting a different error than before when running versions from 23 days ago ([see above comment](https://github.com/swimlane/ngx-datatable/issues/1699#issuecomment-520957242)). Now I'm getting a few errors like this (for every Module that imports `ngx-datatable`):

> node_modules/@swimlane/ngx-datatable/lib/ngx-datatable.module.d.ts(2,22): error TS-996002: Appears in the NgModule.imports of AdminModule, but could not be resolved to an NgModule class

**Comment by whyboris** [comment] 2019-09-05 16:12
I wish someone else can confirm -- in our project with the _latest_ versions of _angular_ and `16.0.0` I get this error now:
```
An unhandled exception occurred: Cannot destructure property `createHash` of 'undefined' or 'null'.
See "/private/var/folders/32/pqw73fv945dcd6n_g619n7f8c_tzhw/T/ng-qSFBT3/angular-errors.log" for further details.
```
Logs:
```
[error] TypeError: Cannot destructure property `createHash` of 'undefined' or 'null'.
    at Object.<anonymous> (/Users/byakubchik/Desktop/WIP/angular8/node_modules/mini-css-extract-plugin/dist/index.js:22:9)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/byakubchik/Desktop/WIP/angular8/node_modules/mini-css-extract-plugin/dist/cjs.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/byakubchik/Desktop/WIP/angular8/node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/styles.js:14:30)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
```

**Comment by WillHall** [comment] 2019-09-05 17:50
@whyboris https://github.com/webpack-contrib/mini-css-extract-plugin/issues/69

**Comment by mhadji** [comment] 2019-09-05 18:06
i get
Error: Failed to find '@swimlane/ngx-datatable/release/index.css'
after installing 16.0.0

**Comment by marjan-georgiev** [comment] 2019-09-05 19:32
@mhadji see https://github.com/swimlane/ngx-datatable/issues/1741

I released a fix in 16.0.1. There is no release folder any more, everything is in the root, and some paths have changed, hence the major version.

**Comment by whyboris** [comment] 2019-09-06 16:32
I'm still debugging issues with _angular-cli_ (https://github.com/angular/angular/issues/32466) ... but with `16.0.2` and a manual update of `webpack` and `webpack-dev-server` I am getting to a new error:
```
ERROR in Error: Assertion error: failed to find directive with exportAs: ngForm
    at /Users/byakubchik/Desktop/WIP/angular8/node_modules/@angular/compiler/bundles/compiler.umd.js:28622:31
    at Array.forEach (<anonymous>)
    at DirectiveBinder.visitElementOrTemplate (/Users/byakubchik/Desktop/WIP/angular8/node_modules/@angular/compiler/bundles/compiler.umd.js:28605:29)
    at DirectiveBinder.visitElement (/Users/byakubchik/Desktop/WIP/angular8/node_modules/@angular/compiler/bundles/compiler.umd.js:28579:76)
    at Element.visit (/Users/byakubchik/Desktop/WIP/angular8/node_modules/@angular/compiler/bundles/compiler.umd.js:4159:71)
    at /Users/byakubchik/Desktop/WIP/angular8/node_modules/@angular/compiler/bundles/compiler.umd.js:28651:67
    at Array.forEach (<anonymous>)
    at DirectiveBinder.visitElementOrTemplate (/Users/byakubchik/Desktop/WIP/angular8/node_modules/@angular/compiler/bundles/compiler.umd.js:28651:27)
    at DirectiveBinder.visitElement (/Users/byakubchik/Desktop/WIP/angular8/node_modules/@angular/compiler/bundles/compiler.umd.js:28579:76)
    at Element.visit (/Users/byakubchik/Desktop/WIP/angular8/node_modules/@angular/compiler/bundles/compiler.umd.js:4159:71)
    at /Users/byakubchik/Desktop/WIP/angular8/node_modules/@angular/compiler/bundles/compiler.umd.js:28651:67
    at Array.forEach (<anonymous>)
    at DirectiveBinder.visitElementOrTemplate (/Users/byakubchik/Desktop/WIP/angular8/node_modules/@angular/compiler/bundles/compiler.umd.js:28651:27)
    at DirectiveBinder.visitTemplate (/Users/byakubchik/Desktop/WIP/angular8/node_modules/@angular/compiler/bundles/compiler.umd.js:28580:78)
    at Template.visit (/Users/byakubchik/Desktop/WIP/angular8/node_modules/@angular/compiler/bundles/compiler.umd.js:4177:72)
    at /Users/byakubchik/Desktop/WIP/angular8/node_modules/@angular/compiler/bundles/compiler.umd.js:28651:67
```
I'll keep debugging 🤷‍♂

**Comment by ronaldohoch** [comment] 2019-11-29 14:27
Hello!
Works fine to me when I updated to the last version, with Ivy enabled.

> "@angular/core": "^8.2.14"
> "@swimlane/ngx-datatable": "^16.0.2"

Thank You all!

**Comment by whyboris** [comment] 2019-11-29 14:30
Sorry I forgot to update this issue -- I was able to get `ngx-datatable` to work with Angular Ivy sometime earlier this month 👌 I strongly suspect the issue is solved 👍

**Comment by osmanmeer** [comment] 2020-01-16 21:15
I just upgraded our app from angular 7 to angular 9. Both dev and prod builds are fine. But when I run it, I get this error. And I'm doing just "ng serve", not sure why it says production use case. I also tried "ng serve --aot", still same error. I'm on 9.0.0-rc.9 version.
Anyone else getting this error after an upgrade? 

ERROR Error: Angular JIT compilation failed: '@angular/compiler' not loaded!
  - JIT compilation is discouraged for production use-cases! Consider AOT mode instead.
  - Did you bootstrap using '@angular/platform-browser-dynamic' or '@angular/platform-server'?
  - Alternatively provide the compiler with 'import "@angular/compiler";' before bootstrapping.
    at getCompilerFacade (core.js:535)
    at Function.get (core.js:12193)
    at getInjectableDef (core.js:322)
    at R3Injector.push../node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js.R3Injector.get (core.js:12494)
    at injectInjectorOnly (core.js:785)
    at ɵɵinject (core.js:790)
    at Object.WhMessageHandlerService_Factory [as factory] (wheels-wh-common-service.js:582)
    at R3Injector.push../node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js.R3Injector.hydrate (core.js:12684)
    at R3Injector.push../node_modules/@angular/core/__ivy_ngcc__/fesm5/core.js.R3Injector.get (core.js:12507)
    at injectInjectorOnly (core.js:785)

**Comment by olcaydaser** [comment] 2020-04-30 20:58
It seem besy way to use this library in angular 9+ is disabling Ivy renderer.
For this you can look at https://angular.io/guide/ivy#opting-out-of-ivy-in-version-9
