### ISSUE TITLE
for more columns (columns), very slow, more than 10 seconds

### ISSUE THREAD

**Issue by xhe** [swimlane/ngx-datatable#618] opened 2017-03-22 07:04 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**

Hello,
I noticed that if I am displaying more than 20 columns, an around 50 rows, the display speed is very slow, taking upto 10 seconds to show.
Can you update some demo by adding more columns and see if you can render table at same speed?
Thanks
**Expected behavior**

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Table version:** 0.7.x

* **Angular version:** 2.0.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by tmburnell** [comment] 2017-03-22 12:21
I am neither confirming the issue or denying the issue but here is what I have seen (being new to this grid).
I have 32 columns and have only tested with 4 rows:
took about 100 ms to load the grid (with no data).
took 200 ms to load the data into the grid after ajax call finished. 
but waited 200 ms for the request to come back (using a node server for mocking).  So would take even longer if a true back-end.

**Comment by amcdnl** [comment] 2017-03-22 13:14
Dupe of https://github.com/swimlane/ngx-datatable/issues/582

**Closed by amcdnl** 2017-03-22 13:14 UTC

**Comment by xhe** [comment] 2017-03-22 15:56
Hello,
I am using the simple demo code, just with 20 columns, like this:

 tableColumns = [

        { prop: 'name' },

        { name: 'name1' },

        { name: 'name2' },

        { name: 'name3' },

        { name: 'name4' },

        { name: 'name5' },

        { name: 'name6' },

        { name: 'name7' },

        { name: 'name8' },

        { name: 'name9' },

        { name: 'name10' },

        { name: 'name11' },

        { name: 'name12' },

        { name: 'name13' },

        { name: 'name14' },

        { name: 'name15' },

        { name: 'name16' },

        { name: 'name17' },

        { name: 'name18' },

        { name: 'name19' },

        { name: 'name20' }

    ];

Then fake very simple data like this:


{

            name: 'Frank', name1: 'name1', name2: 'name2', name3: 'name3',
name4: 'name4', name5: 'name5', name6: 'name6', name7: 'name7', name8:
'name8', name9: 'name9', name10: 'name10',

            name11: 'name11', name12: 'name12', name13: 'name13', name14:
'name14', name15: 'name15', name16: 'name16', name17: 'name7', name18:
'name8', name19: 'name9', name20: 'name10'

        },

jsut repeat it by 20 or more rows.

Then loading is taking longer and longer time.

Then issue is there should be no dependency on how may rows and how many
columns be loaded, as it is virtual dom. I tested facebook fixed data
table, and that worked really fine.

So the result is the more columns, the slower speed loading.

May I ask if the rows is also rendered as virtual dom?

**Comment by xhe** [comment] 2017-03-22 15:58
Oh, a good hints, after I enable the productionMode, this isssue is gone!
Thanks for your suggestions.
