### ISSUE TITLE
when using pagination and switching to page>1, and then filtering the rows, no results are shown

### ISSUE THREAD

**Issue by rotemx** [swimlane/ngx-datatable#375] opened 2016-12-19 13:47 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug 

**Current behavior**
When using pagination, and switching to page>1, and then filtering data, the filtered data is not shown (unless there is enough data to populate the pages)


**Expected behavior**
I think the table should switch back to page 1 on data change or via a manual method call.


**Reproduction of the problem**
see plunker :
https://plnkr.co/edit/cQKNI9cDMkLCJrcWtdcK

click "page 2" and then click "filter data". the data is gone although there is one record.

**What is the motivation / use case for changing the behavior?**
I need to combine pagination and data filtering on the table.

**Please tell us about your environment:**
latest

* **Table version:** 0.7.x
latest

* **Angular version:** 2.0.x
latest

Browser : Chrome

**Comment by imVinayPandya** [comment] 2016-12-20 09:55
yes I am facing the same problem I want to switch page 1 programmatically

**Expected behavior**
I think the table should switch back to page 1 on data change or via a manual method call.

**Comment by santhosh1a32** [comment] 2017-02-15 09:42
I am also facing same issue. If I go to page > 1, then filter is not working. Is there any solution for this.?

**Comment by pravinh-menlo** [comment] 2017-02-16 09:34
Any solution ?

**Comment by santhosh1a32** [comment] 2017-02-23 13:17
@imVinayPandya .. How to do it programatically..?

**Comment by deeg** [comment] 2017-02-27 01:34
This is a duplicate of #515

**Closed** 2017-02-28 12:46 UTC
Labels: Investigate
