### ISSUE TITLE
swimlane/ngx-datatable is active ?

### ISSUE THREAD

**Issue by kamlesh0606** [swimlane/ngx-datatable#1669] opened 2019-04-03 12:22 UTC
Hi,

Please share your Repository Status .

Thanks
kamlesh

**Comment by darkurse** [comment] 2019-04-03 14:36
I was thinking exactly the same. There are so many fixes that were never addressed it is maddening.
600+ open issues , 63+ PR stale for months  !!!!!!! That's .. sad.

So yes please share your repo status so we will now if we need to move onto something else !

**Comment by dstj** [comment] 2019-04-04 17:57
While I whole heartedly agree and await the answer, this is a duplicate of #1661

**Comment by antch** [comment] 2019-04-11 20:07
Sad to say, but this project appears to be dead in the water.

**Comment by bleuscyther** [comment] 2019-04-11 21:03
:) you can dm the owner on twitter if you want to be a contributor

**Comment by marjan-georgiev** [comment] 2019-04-11 21:19
Hi all, I left a comment on: https://github.com/swimlane/ngx-datatable/issues/1669

Closing this one. Thank you!

**Closed by marjan-georgiev** 2019-04-11 21:19 UTC

**Comment by bleuscyther** [comment] 2019-04-22 07:11
Thank you for this great project, you wanted to say that link i think https://github.com/swimlane/ngx-datatable/issues/1661
