### ISSUE TITLE
Columns headers get missed up when having dri="rtl" with scrollbar and many rows

### ISSUE THREAD

**Issue by ihabZhaika** [swimlane/ngx-datatable#227] opened 2016-10-25 20:24 UTC
```
[x ] bug report => search github for a similar issue or PR before submitting

```

**Current behavior**

if i put right to left attribute { dir="rtl""} , and have scrollbarH: true , the column names get missed up { should have enough columns to fill the page width and get the scroller}

**Expected behavior**
they should appear  as dir="ltr"

**Reproduction of the problem**
http://plnkr.co/edit/7QDJOI

scroll the hBar to end then to start , then check the headers

**What is the motivation / use case for changing the behavior?**

any language that is right to left

**Comment by amcdnl** [comment] 2016-10-26 12:35
We don't currently support RTL and to be honest no use case on my side for it in the near future. Happy to accept a PR though.

**Comment by amcdnl** [comment] 2017-04-15 13:15
RTL isn't supported. I'd say this is a dupe of #87

**Closed by amcdnl** 2017-04-15 13:15 UTC
Labels: Accepting PRs, Enhancement, Working as Intended

**Comment by hamidpp** [comment] 2024-09-18 16:27
you use this styles to set rtl:

```
.ngx-datatable.dark .datatable-header .datatable-header-cell,
.ngx-datatable.dark .datatable-body .datatable-body-row .datatable-body-cell {
  text-align: right;
}
```
