### ISSUE TITLE
Sorting+paging: after sorting the page-button 1 becomes always active

### ISSUE THREAD

**Issue by nazaroid** [swimlane/ngx-datatable#1314] opened 2018-02-28 08:00 UTC
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
When I select page 3(for example) on pagination and sort by any column, the grid after the sorting is done sets the button for page 1 to be active. My current data set displays the rows for page 3 at the moment and the component property that is bound to [offset] is set to 3.

**Expected behavior**
I expect that after handling the event (sort), an active page-button that is set in the property (offset), but is not 1. I'm using an external oData-source (externalPaging = true; externalSorting = true) and setting page button to 1 after sorting in my case makes no sense.

**Reproduction of the problem**
* Take your example http://swimlane.github.io/ngx-datatable/#server-paging
* navigate to page 3
* sort by any column and you see that page active page will reset to 1. For my case this is incorrect behavior, but i can't change it.

These guys have the same issue:
https://github.com/swimlane/ngx-datatable/issues/1107

**Comment by maxtacco** [comment] 2018-03-23 13:07
I think this is a duplicate of https://github.com/swimlane/ngx-datatable/issues/765

**Comment by ShinDarth** [comment] 2018-04-16 20:51
Confirmed. I have exactly the same issue.

**Comment by farhanmughal222** [comment] 2018-12-05 10:55
is there any update on this issue?

**Comment by zeevkatz** [comment] 2018-12-18 15:08
Any Updates?

**Comment by Nouman24** [comment] 2019-03-11 13:20
any alternative solution for this issue?

**Closed** 2021-04-20 21:56 UTC

**Comment by salwagt** [comment] 2021-09-13 08:49
<ngx-datatable
#tableRows
(sort)="onSort($event)"
...

@ViewChild('tableRows') table: any;

Try to add this in onSort() function:
this.table.bodyComponent.updateOffsetY(this.page.offset);
this.table.offset = this.page.offset;
