### ISSUE TITLE
ngc Error: Compilation failed. Resource file not found: ~/projects/web/node_modules/@swimlane/ngx-datatable/release/components/datatable.component.scss

### ISSUE THREAD

**Issue by DethAriel** [swimlane/ngx-datatable#477] opened 2017-01-31 01:08 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
When running `ngc`, this error pops up:
```
Error: Compilation failed. Resource file not found: ~/projects/web/node_modules/@swimlane/ngx-datatable/release/components/datatable.component.scss
```

**Expected behavior**
There should be no error

**Reproduction of the problem**
```json
// package.json
{
  "name": "ngx-datatable-bug",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "ngc": "ngc -p tsconfig-aot.json"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@angular/common": "2.4.5",
    "@types/core-js": "0.9.34",
    "@angular/compiler": "2.4.5",
    "@angular/compiler-cli": "2.4.5",
    "@angular/core": "2.4.5",
    "@angular/forms": "2.4.5",
    "@angular/http": "2.4.5",
    "@angular/platform-browser": "2.4.5",
    "@angular/platform-browser-dynamic": "2.4.5",
    "@angular/platform-server": "2.4.5",
    "@angular/router": "3.4.5",
    "@swimlane/ngx-datatable": "6.0.1",
    "rxjs": "5.0.2",
    "zone.js": "0.7.4",
    "typescript": "2.0.3"
  }
}
```

```ts
// src/main.ts
import { Component, NgModule, enableProdMode } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { NgxDatatableModule } from '@swimlane/ngx-datatable';

@NgModule({
    bootstrap: [AppComponent],
    declarations: [
        AppComponent,
    ],
    imports: [
        BrowserModule,
        NgxDatatableModule,
    ],
})
export class AppModule { }

@Component({
    selector: 'my-app',
    template: `
    `,
}) export class AppComponent { }

enableProdMode();

platformBrowserDynamic().bootstrapModule(AppModule);
```

```json
// tsconfig-aot.json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es2015",
        "experimentalDecorators": true,
        "noImplicitAny": false,
        "sourceMap": false
    },
    "files": [
        "./src/main.ts"
    ],
    "angularCompilerOptions": {
        "genDir": "aot",
        "skipMetadataEmit": true
    }
}
```

Steps to reproduce:
1. Create above files
2. `npm install`
3. `npm run ngc`

**Please tell us about your environment:**
OS: MacOS Sierra 10.12.3
IDE: VSCode
Package manager: npm 4.0.5
NodeJS: v7.4.0

* **Table version:** 6.0.1

* **Angular version:** 2.4.5

* **Browser:** not applicable

* **Language:** TypeScript 2.0.3

**Comment by amcdnl** [comment] 2017-01-31 13:04
dupe of #459

**Closed by amcdnl** 2017-01-31 13:04 UTC
