### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined ( allRowsSelected )

### ISSUE THREAD

**Issue by darkurse** [swimlane/ngx-datatable#1141] opened 2017-11-20 17:28 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**

since version 11.1.x I have the following error in console

```
DatatableComponent.html:5 ERROR TypeError: Cannot read property 'length' of undefined
    at DatatableComponent.get [as allRowsSelected] (index.js:4867)
    at Object.eval [as updateDirectives] (DatatableComponent.html:18)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js:14339)
    at checkAndUpdateView (core.js:13508)
    at callViewAction (core.js:13858)
    at execEmbeddedViewsAction (core.js:13816)
    at checkAndUpdateView (core.js:13509)
    at callViewAction (core.js:13858)
    at execComponentViewsAction (core.js:13790)
    at checkAndUpdateView (core.js:13514)
```

It seems to be a new feature, so maybe some issues there ? I haven't changed my code since 11.0.4 which is as follow :

```html

<ngx-datatable
    class="material fullscreen"                        
    [columnMode]="'force'"
    [rowClass]="getRowClass"
    [headerHeight]="50"
    [footerHeight]="50"
    [rowHeight]="50"
    [externalPaging]="true"
    [externalSorting]="true"
    [loadingIndicator]="loading"
    [limit]="pageSize"
    [offset]="pageOffset"
    [count]="totalCount"
    [rows]="items"
    [columns]="columns"

    [messages]="{emptyMessage: 'DataTable.EmptyMessage' | translate, totalMessage: 'DataTable.Total' | translate, selectedMessage: 'DataTable.SelectedMessage' | translate}"
    (page)="onPageChanged($event)"
    (sort)="onSortChanged($event)"
    (scroll)="onScroll($event.offsetY)"
    (reorder)="onColumnsReordered($event)">

    <!-- Header template -->
    <ng-template #headerTemplate let-column="column" let-sort="sortFn">
        <span class="datatable-header-cell-wrapper"><span class="datatable-header-cell-label draggable text-truncate" (click)="sort()">{{ column.name | translate }}</span></span>
    </ng-template>

    <!-- Cell template -->
    <ng-template #cellTemplate let-column="column" let-value="value">
        <div [innerHTML]="getCellHtml(value, column)"></div>
    </ng-template>

    <!-- Actions template -->
    <ng-template #actionTemplate let-row="row" let-value="value">
        <button mat-icon-button (click)="onDeleteClick(value)" [attr.disabled]="!canDelete" color="warn" matTooltip="{{'CRM.Delete' | translate}}" [matTooltipPosition]="'below'">
            <i class="material-icons">delete</i>
        </button>
        <button mat-icon-button (click)="onEditClick(value)" [attr.disabled]="!canEdit" matTooltip="{{'CRM.Edit' | translate}}" [matTooltipPosition]="'below'">
            <i class="material-icons">create</i>
        </button>
    </ng-template>
    
</ngx-datatable>

```

**Please tell us about your environment:**

win10 pro, vscode, npm, node

* **Table version:** 0.8.x

11.1.2

* **Angular version:** 2.0.x

5.0.2

* **Browser:** 

chrome 62.0.3202.94

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
typescript 2.6.1

**Comment by 202chaz** [comment] 2017-11-20 17:43
@darkurse use release 11.1.2 I was getting the same error

**Comment by amcdnl** [comment] 2017-11-20 19:48
fixed in latest :)

**Comment by markwaddle** [comment] 2017-11-21 22:56
which PR fixes this? i can still reproduce on 11.1.2

**Comment by darkurse** [comment] 2017-11-22 09:37
@markwaddle , ensure you do have the latest version installed with `npm list @swimlane/ngx-datatable` ?

**Comment by amcdnl** [comment] 2017-11-22 13:33
Is anyuone else still getting this?

**Closed** 2017-11-22 13:33 UTC

**Comment by darkurse** [comment] 2017-11-22 14:00
I'm good now. Thanks

**Comment by markwaddle** [comment] 2017-11-22 15:29
I am definitely running 11.1.2. My issue may be another bug with a similar symptom. I have <input>s in the header cells. When editing text in the inputs it was triggering the select event on the table 3 times in succession, every time I changed the text selection in the box. Once with every item as selected, once with no items, and once with the selected as undefined. The last one was causing errors in the data table code. I realized yesterday that <input> has a select event, and the listeners in datatable aren’t discrete enough to exclude the event coming from the inputs. I added handlers to swallow the select event from the inputs as a workaround for now.

**Comment by markwaddle** [comment] 2017-11-22 15:33
GitHub removed the tags from my comment above.
Corrected: I am definitely running 11.1.2. My issue may be another bug with a similar symptom. I have input elements in the header cells. When editing text in the inputs it was triggering the select event on the table 3 times in succession, every time I changed the text selection in an input. Once with every item as selected, once with no items, and once with the selected as undefined. The last one was causing errors in the data table code. I realized yesterday that input has a select event, and the listeners in datatable aren’t discrete enough to exclude the event coming from the inputs. I added handlers to swallow the select event from the inputs as a workaround for now.

**Comment by BrummbQ** [comment] 2017-11-27 09:36
@amcdnl  I can still reproduce this issue in a test if I set rows to undefined.

**Comment by MarcusCalidus** [comment] 2017-11-28 11:39
@amcdnl Hi Austin. I still get the error with 11.1.4. It works with 11.0.4 though.

**Comment by adskiremote** [comment] 2017-11-30 03:53
me too - Version 11.1.4 receiving the same error.

**Comment by bobsov** [comment] 2017-12-01 08:49
11.1.5 still has this issue. Reverted to 11.0.4 and all good there.

**Comment by darkurse** [comment] 2017-12-01 09:24
Actually I still have issues with the latest versions .. I've reverted back to 11.0.4 for a while too.

**Comment by aog1971** [comment] 2017-12-01 12:19
Me too - Version 11.1.4 receiving the same error.
The problem in my case is because an uninitialized object is assigned to the [row] property or it is not an array type.

In my html:
<ngx-datatable class = "material"
    [rows] = "customers"
    [loadingIndicator] = "loadingIndicator">
.....


In my component.ts:

public customers: any; // **<- here's the problem**
....


The solution, assign an object of type initialized array:

In my component.ts:

public customers: Array <any> = new Array <any> (); // **<- solution**
....

The best solution is to initialize the array of the customer type
public customers: Array <customer> = new Array <customer> ();

I hope you seriva for help, I have solved the problem.

**Comment by MarcusCalidus** [comment] 2017-12-01 14:18
@aog1971 Thank you for the hint. That helped a lot. 

There is also the same kind of problem when using async input for the rows. If the Observable returns undefined instead of an empty array the exception is thrown.

**Comment by brandon-applied** [comment] 2017-12-08 21:58
I'm still seeing this issue with 11.1.5. Any update on when a build with this fix will be pushed to NPM?

**Comment by sheldonyss** [comment] 2017-12-11 09:09
Me too having the same error with 11.1.5

**Comment by rubenheymans** [comment] 2017-12-11 19:10
I'm having the same issue with 11.1.5, probably because the rows: Observable<User[]>; is empty at first

**Comment by NauxLiu** [comment] 2017-12-12 01:51
@amcdnl. I'm having the same issue with 11.1.5

**Comment by fergalmoran** [comment] 2017-12-12 16:40
Same with 11.1.5 - reverting to 11.0.4 resolved.

**Comment by MeForThis** [comment] 2017-12-15 12:47
Same with 11.1.5 too - reverting to 11.0.4 also resolved the problem

**Comment by bobsov** [comment] 2017-12-15 16:03
Make sure the array is initialized with empty array, that way, you don't have to go back to 11.0.4.

**Comment by fergalmoran** [comment] 2017-12-15 18:46
@bobsov That won't work for me as I'm consuming an Observable<T[]>

**Comment by adamlepkowski** [comment] 2017-12-17 16:18
As aog1971 said initialize your "rows" array in the component constructor, then it works. Generally, we cannot assign undefined array to control.

**Comment by rubenheymans** [comment] 2017-12-17 21:19
can you provide a working example please?
rows: Observable<User[]>;
constructor:
this.rows = new Observable<User[]>();

this.rows = this.usersCollection.valueChanges();

is not working, same error

**Comment by MeForThis** [comment] 2017-12-18 07:33
Gave it another try this morning. Installed 11.15 again and everything works, without changing one line of code ...

**Comment by khalilof** [comment] 2017-12-21 13:10
I can't get rid of this issue 
I just followed the getting started page and the very first example keeps showing this error :
TypeError: Cannot read property 'length' of undefined
    at DatatableComponent.get [as allRowsSelected] (vendor.bundle.js:sourcemap:17581)

any real solution for this ?

**Comment by amcdnl** [comment] 2017-12-22 21:30
Try 11.1.7 plz

**Comment by rubenheymans** [comment] 2017-12-23 16:29
it's working, thanks!

**Comment by adskiremote** [comment] 2017-12-23 16:41
Me too now after update its all good.  Thank you 😁

**Comment by hlpupo** [comment] 2018-01-11 03:50
I had the same problem, update to v 11.1.7 the problem was resolved

**Comment by infact** [comment] 2018-05-08 13:55
I am using      "@swimlane/ngx-datatable": "^11.2.0",
I still see the same error  ---- "Cannot read property 'length' of undefined ..." 

Any suggestions please?

**Comment by infact** [comment] 2018-05-08 14:39
I even tried with version 11.1.7   "@swimlane/ngx-datatable": "^11.1.7", and still see the same error 
<img width="926" alt="length3" src="https://user-images.githubusercontent.com/9020432/39763811-b89212fe-52a3-11e8-8b7d-e3a70026b539.PNG">

**Comment by mtpultz** [comment] 2018-06-12 16:02
I'm running version v11.3.2 and I've got the same error on the same line

**Comment by htrex** [comment] 2018-10-10 16:58
I'm seeing this error on version 13.1.0, it's triggered when selecting some text in a text field input placed inside a detail row.

@markwaddle it seems I'm facing the same problem, can you please post your workaround here?

```
DatatableComponent.html:5 ERROR TypeError: Cannot read property 'length' of undefined
    at DatatableComponent.get [as allRowsSelected] (index.js:3246)
    at Object.eval [as updateDirectives] (DatatableComponent.html:19)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js:11054)
    at checkAndUpdateView (core.js:10451)
    at callViewAction (core.js:10692)
    at execEmbeddedViewsAction (core.js:10655)
    at checkAndUpdateView (core.js:10452)
    at callViewAction (core.js:10692)
    at execComponentViewsAction (core.js:10634)
    at checkAndUpdateView (core.js:10457)
View_DatatableComponent_1 @ DatatableComponent.html:5
push../node_modules/@angular/core/fesm5/core.js.DebugContext_.logError @ core.js:11306
push../node_modules/@angular/core/fesm5/core.js.ErrorHandler.handleError @ core.js:1719
(anonymous) @ core.js:4578
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:388
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:138
push../node_modules/@angular/core/fesm5/core.js.NgZone.runOutsideAngular @ core.js:3779
push../node_modules/@angular/core/fesm5/core.js.ApplicationRef.tick @ core.js:4578
(anonymous) @ core.js:4462
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:388
onInvoke @ core.js:3820
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:387
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:138
push../node_modules/@angular/core/fesm5/core.js.NgZone.run @ core.js:3734
next @ core.js:4462
schedulerFn @ core.js:3551
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub @ Subscriber.js:196
push../node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next @ Subscriber.js:134
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber._next @ Subscriber.js:77
push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next @ Subscriber.js:54
push../node_modules/rxjs/_esm5/internal/Subject.js.Subject.next @ Subject.js:47
push../node_modules/@angular/core/fesm5/core.js.EventEmitter.emit @ core.js:3535
checkStable @ core.js:3789
onLeave @ core.js:3856
onInvokeTask @ core.js:3814
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:420
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:188
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:496
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566
```

**Comment by SuganNaickerf** [comment] 2018-11-15 05:02
Hi.  I was experiencing the length is null issue as well, eventually I realized that I was missing the  following :

selected = [];

I was using **selected** in my HTML, but I did not initialize the selected variable, after I added the initialize it worked, no further length undefined issues, on V14.0.0 of ngxdatatables.

**Comment by RamkiPannerselvam** [comment] 2019-03-20 07:31
initialize the variable that you are trying to send. 
it could be one of the values expected by ngx-data table ; 

Selected = [];

**Comment by sachin5590** [comment] 2019-04-12 07:14
I am also getting a similar error:
ERROR TypeError: Cannot read property 'length' of undefined
    at Object.eval [as updateDirectives] (DatatableComponent.html:76)
    at Object.debugUpdateDirectives [as updateDirectives] (core.js:11054)
    at checkAndUpdateView (core.js:10451)
    at callViewAction (core.js:10692)
    at execEmbeddedViewsAction (core.js:10655)
    at checkAndUpdateView (core.js:10452)
    at callViewAction (core.js:10692)
    at execComponentViewsAction (core.js:10634)
    at checkAndUpdateView (core.js:10457)
    at callViewAction (core.js:10692)

When I check DatatableComponent.html:76
It has:
[selectedCount]="selected.length"
In my component I have initialized selected = []; 
But then also I am getting the error. Any suggestion ?

**Comment by adskiremote** [comment] 2019-04-12 17:17
Experienced this myself.  As @RamkiPannerselvam  said - make sure you declare your variables with a starting empty array = [].

If you still are can you better describe or show your code how you're constructing your table please.

**Comment by sachin5590** [comment] 2019-04-15 05:32
I have found the issue. The issue is I am using rowDetail and select event in the table, so if I try to select the text in row detail. Then select event of row selection gets fired which was making selected undefined.
