### ISSUE TITLE
Accessibility Support (Question)

### ISSUE THREAD

**Issue by Codermar** [swimlane/ngx-datatable#476] opened 2017-01-30 22:38 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
What is the current Accessibility compliance of ngrx-datatables and what's the current road map to get to that?

**Expected behavior**
ngrx-datatables should be fully Accessible

**What is the motivation / use case for changing the behavior?**

* **Table version:** 5.x or 6.x

* **Angular version:** 2.x

**Comment by amcdnl** [comment] 2017-01-31 13:09
Dupe of #257

**Closed by amcdnl** 2017-01-31 13:09 UTC
Labels: Duplicate
