### ISSUE TITLE
Add tabindex for header to support 508 compliance not working

### ISSUE THREAD

**Issue by cxzdaddy** [swimlane/ngx-datatable#856] opened 2017-07-10 20:02 UTC
For the <ngx-datatable-column>html template , I want to add html attribute 'tabindex' to support 508 not working for me . Also the pagination can not hit enter or keyboard event to go to next page. Any one can help me on this ?

**Comment by amcdnl** [comment] 2017-08-04 13:52
Dupe of broader issue logged.

**Closed by amcdnl** 2017-08-04 13:52 UTC
