### ISSUE TITLE
Row overlapping when dynamic row height or virtualization.

### ISSUE THREAD

**Issue by torabshaikh** [swimlane/ngx-datatable#1597] opened 2018-11-13 12:59 UTC
**I'm submitting a
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
Sometimes two row are overlapping each other while scrolling or hovering. This is happening when the `rowHeight ` is dynamic or `virtualization ` flag is `true`. I am attaching screenshots of the problem.

**Expected behavior**
Row should not overlap each other.

**Reproduction of the problem**
Visit [virtual-paging](http://swimlane.github.io/ngx-datatable/#virtual-paging) or [Dynamic Row Height](http://swimlane.github.io/ngx-datatable/#dynamic) scroll down to the end of the table then scroll up and down until it shows the mentioned problem. 

**What is the motivation / use case for changing the behavior?**
<!-- Describe the motivation or the concrete use case -->

**Please tell us about your environment:**
<!-- Operating system, IDE, package manager, HTTP server, ... -->
Windows 10
Node: 8.11.2

* **Table version:** 
<!-- Check whether this is still an issue in the most recent table version -->
14.0.0

* **Angular version:** 
<!-- Check whether this is still an issue in the most recent Angular version -->
Angular CLI: 6.1.4
Angular: 7.0.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome
<!-- All browsers where this could be reproduced -->

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

![screenshot 37](https://user-images.githubusercontent.com/18557453/48415073-6618f600-e772-11e8-913f-d6c37ad47536.png)
![screenshot 38](https://user-images.githubusercontent.com/18557453/48415074-6618f600-e772-11e8-80a0-71de63940655.png)

**Comment by pwinstead** [comment] 2018-11-13 13:05
Looks to be the same issue described in this other issue.

Duplicate of #1594

**Comment by torabshaikh** [comment] 2018-11-13 13:11
Okay. The title is misleading so I didn't if this Issue was created before. :')
So this is a problem of Chrome not ngx-datatable?
Thanks for your quick reply BTW.

**Comment by pwinstead** [comment] 2018-11-13 13:22
I've only been able to produce the issue on Chrome. IE and Edge both render correctly.  I agree title in the other bug could have been more descriptive of the issue.

**Comment by torabshaikh** [comment] 2018-11-13 14:23
@pwinstead I guess we will see if the issue is because of Chrome's new update or `ngx-datatable`. Thanks for your valuable info. 👍

**Comment by mfjharvey** [comment] 2018-11-16 12:36
I've posted a potential workaround for this [here](https://github.com/swimlane/ngx-datatable/issues/1594#issuecomment-439379643).

**Comment by torabshaikh** [comment] 2019-01-02 12:13
@mfjharvey Thanks for your reply. I have used your patch with a different class and now the problem seems to be reduced as it still overlaps for a fraction of a second. I am posting my answer here for future visitors.
```
 .datatable-body-cell {
     will-change: transform;
}
```

**Closed** 2019-01-02 12:13 UTC
