### ISSUE TITLE
Angular 5 support

### ISSUE THREAD

**Issue by osnoser1** [swimlane/ngx-datatable#1082] opened 2017-10-27 11:56 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, post on Stackoverflow or Gitter
```

**Current behavior**
Warnings with `peerDependencies`.

**Expected behavior**
No warnings with `peerDependencies`.

**What is the motivation / use case for changing the behavior?**
Support for Angular 5.

* **Table version:** 10.3.0

* **Angular version:** Angular 5.0.0.rc-7

**Comment by amcdnl** [comment] 2017-10-27 14:06
Once Angular5 is out, we will cut a new version to support that. It should work as is now with the warnings.

**Comment by osnoser1** [comment] 2017-11-02 05:37
Angular 5 is out! 🎉

**Comment by amcdnl** [comment] 2017-11-02 18:07
Plan to have a release with it by end of tomorrow.

**Comment by wizarrc** [comment] 2017-11-02 18:16
@amcdnl have you tested the row group demo with Angular 5? In testing of my fork, Angular 5's `NgTemplateOutlet` changes break that demo page. I have yet to root cause it.

**Comment by amcdnl** [comment] 2017-11-02 18:27
I believe that API was deprecated and removed in v5. Look at the commits, Rob Wormall made a change somewhere else to resolve this in this lib.

**Comment by wizarrc** [comment] 2017-11-02 18:38
@amcdnl I was referring to the class. I believe the property `ngOutletContext` has been removed. In my case I was referring to the changes in method `ngOnChanges` in the class `NgTemplateOutlet` class which is marked as stable.

https://github.com/angular/angular/blob/master/packages/common/src/directives/ng_template_outlet.ts#L59
```
if (this._viewRef && this.ngTemplateOutletContext) {
        this._updateExistingContext(this.ngTemplateOutletContext);
}
```
That code path was causing issues for me in the row group demo. Just something to keep an eye on as you upgrade to Angular 5.

**Comment by bendg25** [comment] 2017-11-04 15:28
Any update on this?  I need this Angular 5 support.

**Comment by amcdnl** [comment] 2017-11-04 16:36
Latest version with ng5 support is published

**Closed by amcdnl** 2017-11-04 16:36 UTC

**Comment by osnoser1** [comment] 2017-11-06 13:55
Hi, `peerDependencies` were not updated ... 😯

**Comment by arsyed04** [comment] 2017-11-07 05:18
I see new code merged, but not a new version on npm. It is still 11.0.0

**Comment by amcdnl** [comment] 2017-11-29 13:58
11.1.5 is compiled w/ 4.x so compat will work now.
