### ISSUE TITLE
Switching of pages at server-side paging with filter doesn't work or works from the second time.

### ISSUE THREAD

**Issue by karmis** [swimlane/ngx-datatable#261] opened 2016-11-07 21:41 UTC
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Switching of pages at server-side paging with filter doesn't work or works from the second time. Showing empty area without default 'empty' text (No data to display):

**Expected behavior**
The pager must switched to next page and show new fetched rows

**Reproduction of the problem**
the component code
http://pastebin.com/pA4bYezn

the template code
http://pastebin.com/ncWhjvPX

screenshots
before search:
http://dl1.joxi.net/drive/2016/11/08/0004/1376/279904/04/32943b796c.jpg

on first trying search:
http://dl2.joxi.net/drive/2016/11/08/0004/1376/279904/04/ed5eee6e99.jpg

on second trying search:
http://dl2.joxi.net/drive/2016/11/08/0004/1376/279904/04/e5ebbeec88.jpg

on change page
http://dl1.joxi.net/drive/2016/11/08/0004/1376/279904/04/ad71a0fc9d.jpg

**What is the motivation / use case for changing the behavior?**
I think what it is bug

**Please tell us about your environment:**
Windows10
WebStorm
npm 3.10.8
node v6.8.1

* **Table version:**
1.3.x

* **Angular version:**
2.0.x

* **Browser:**
all

* **Language:** [all | TypeScript X.X | ES6/7 | ES5] 
all

**Comment by amcdnl** [comment] 2016-11-07 23:35
Can you make a demo plunkr?

**Comment by karmis** [comment] 2016-11-08 00:50
it is difficult (
I can as that differently to help to reproduce a problem?

**Comment by karmis** [comment] 2016-11-10 01:05
I cant create the demo plunkr, but can take more info about this bug.
The bug i show an in the demo server-side pager.

So... source code fully from the demo server side pager...
http://pastebin.com/KnfYuu8Y

Current behavior:
ctrl+R (chrome) in component with table(only):
http://dl2.joxi.net/drive/2016/11/10/0004/1376/279904/04/8e0d47c75d.jpg

In markup datatable directive I see it: http://dl1.joxi.net/drive/2016/11/10/0004/1376/279904/04/832046c217.jpg
... 

but after resize browser window all working all right: http://dl2.joxi.net/drive/2016/11/10/0004/1376/279904/04/46299f6c6b.jpg

Fix pls it.

**Comment by amcdnl** [comment] 2016-11-15 15:13
Please retest on latest.

**Comment by karmis** [comment] 2016-11-16 09:34
Im use this solution
https://github.com/swimlane/angular2-data-table/issues/261

**Comment by PatrickHuetter** [comment] 2017-02-04 10:54
I don't know but maybe this is also related to #486

**Comment by deeg** [comment] 2017-02-27 17:10
This is a duplicate of #515. See that issue and associated PR for details.

**Closed** 2017-02-28 12:54 UTC
Labels: Investigate, Need More Info
